In [3]:
import seaborn as sns
iris = sns.load_dataset('iris')

In [12]:
# 1. 결측치가 있는 행을 모두 제거하세요.
iris = iris.dropna(inplace = True)
iris

AttributeError: 'NoneType' object has no attribute 'dropna'

In [8]:
# 2. 중복된 행을 제거하세요.
iris.drop_duplicates(inplace = True)
iris

AttributeError: 'NoneType' object has no attribute 'drop_duplicates'

In [10]:
# 3. 'petal_length'가 5보다 큰 행만 선택하세요.
filtered_iris = iris[iris['petal_length'] > 5]
iris

TypeError: 'NoneType' object is not subscriptable

In [13]:
# 4. 'species'에 따라 데이터를 그룹화하세요.
grouped_iris = iris.groupby('species')
iris

AttributeError: 'NoneType' object has no attribute 'groupby'

In [15]:
# 5. 그룹화한 데이터에서 'sepal_length'의 평균을 계산하세요.
mean_sepal_length = grouped_iris['sepla_length'].mean()
iris

NameError: name 'grouped_iris' is not defined

In [17]:
# 6. 'petal_length'를 기준으로 데이터를 오름차순으로 정렬하세요.
iris.sort_values('petal_length', inplace = True)
iris

AttributeError: 'NoneType' object has no attribute 'sort_values'

In [18]:
# 7. 'petal_width'를 기준으로 데이터를 내림차순으로 정렬하세요.
iris.sort_values('petal_width', ascending = False, inplace = True)
iris

AttributeError: 'NoneType' object has no attribute 'sort_values'

In [19]:
# 8. 'species'의 빈도수를 구하세요.
print(iris['species'].value_counts())

TypeError: 'NoneType' object is not subscriptable

In [20]:
#9. 'species'값 중 'setosa'를 포함하는 행만 선택하세요.
setosa_rows = iris[iris['species'].str.contains('setosa')]
setosa_rows

TypeError: 'NoneType' object is not subscriptable

In [21]:
# 10. 'species' 값이 'setosa'로 시작하는 행을 선택하세요.
setosa_start = iris[iris['species'].str.startswith('setosa')]
setosa_start

TypeError: 'NoneType' object is not subscriptable

In [22]:
# 11. 'species' 값이 'virginica'로 끝나느 행을 선택하세요.
virginica_end = iris[iris['species'].str.endswith('virginica')]
virginica_end

TypeError: 'NoneType' object is not subscriptable

In [23]:
# 12. 'species'의 'setosa'를 'SETOSA'로 대체하세요.
iris['species'] = iris['species'].replace('setosa', 'SETOSA')
iris

TypeError: 'NoneType' object is not subscriptable

In [24]:
# 13. iris 데이터셋에서 'species'열을 제거하세요.
iris.drop('species', axis = 1, inplace = True)
iris

AttributeError: 'NoneType' object has no attribute 'drop'